$(document).ready(function(){
	$("#dropdown").on("click",function(){
		$("#article1").toggle();	
	});
	$("#dropdown").on("mouseover",function(){
		$("#article1").show();	
	});
	$("#go1").click(function(e){
		e.preventDefault();
		$(".hide").hide();	
		$("#article1").hide();	
		$("#article2").show();	
	});
	$("#go2").click(function(e){
		e.preventDefault();
		$(".hide").hide();
		$("#article1").hide();	
		$("#article3").show();
	});
	$("#go3").click(function(e){
		e.preventDefault();
		$(".hide").hide();
		$("#article1").hide();	
		$("#article4").show();
	});
	$("#go4").click(function(e){
		e.preventDefault();
		$(".hide").hide();	
		$("#article1").hide();
		$("#article5").show();
	});
	$("#go5").click(function(e){
		e.preventDefault();
		$(".hide").hide();	
		$("#article1").hide();
		$("#article6").show();
	});
});